name: website

on: 
  push:
    branches: main

jobs:
  LectureNotePages:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install tools
        run: |
          pip3 install sphinx
          pip3 install sphinx_rtd_theme sphinxcontrib-bibtex matplotlib pandas numpy nbsphinx ipykernel sphinx_inline_tabs
          
      - name: Generate sphinx pages
        run: |
          cd sphinx
          make html
          
      - name: install oh my zsh
        run: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}